-- ============================================================================
-- WindFoil Weather Intelligence — Schema Migration 001 (init)
-- File version: 1.0.0   |   App target: v2.5.0   |   Engine: SQLite 3
-- ----------------------------------------------------------------------------
-- AUTH OWNERSHIP NOTE:
--   The `user` table is OWNED and generated by Better Auth (via its own
--   migration/CLI). This file does NOT create it. All domain tables below
--   reference user(id) (TEXT). For LOCAL standalone testing, the test harness
--   (db/schema.test.mjs) creates a minimal `user` stub BEFORE applying this
--   migration so the foreign keys resolve.
--
-- CONVENTIONS:
--   - Primary keys: TEXT UUID (app-generated via crypto.randomUUID) for
--     portability to Postgres later.
--   - Timestamps: TEXT, ISO-8601 UTC (e.g. 2026-06-14T07:30:00Z).
--   - session_date: TEXT, 'YYYY-MM-DD' anchored to the SPOT timezone
--     (not UTC) — this is what enforces the "feedback only for today" rule.
--   - Enums emulated with CHECK constraints.
--   - PRAGMA foreign_keys = ON must be set per-connection (done in db.js).
-- ============================================================================

-- --- Spots --------------------------------------------------------------------
-- Riding locations. user_id NULL => shared/global spot (e.g. seeded Gialova).
CREATE TABLE IF NOT EXISTS spots (
    id           TEXT PRIMARY KEY,
    user_id      TEXT REFERENCES user(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    latitude     REAL NOT NULL,
    longitude    REAL NOT NULL,
    timezone     TEXT NOT NULL DEFAULT 'UTC',     -- IANA tz, e.g. 'Europe/Athens'
    created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_spots_user ON spots(user_id);

-- --- Rider profiles -----------------------------------------------------------
-- Per-user wingfoil profile. The calibrated planing threshold lives here and is
-- updated by the feedback loop (see calibration logic in calibration.js).
CREATE TABLE IF NOT EXISTS rider_profiles (
    user_id                  TEXT PRIMARY KEY REFERENCES user(id) ON DELETE CASCADE,
    weight_kg                REAL,
    skill_level              TEXT CHECK (skill_level IN ('beginner','intermediate','advanced','expert')),
    -- Planing threshold in knots. 'source' tells us whether it is the user's
    -- manual override, or a value derived (rolled) from session feedback.
    planing_threshold_kt     REAL,
    planing_threshold_source TEXT NOT NULL DEFAULT 'default'
                                  CHECK (planing_threshold_source IN ('default','manual','calibrated')),
    updated_at               TEXT NOT NULL
);

-- --- Equipment ----------------------------------------------------------------
-- Migrated out of localStorage now that we have real users. 'size' is m² for
-- wings and cm² for foils — interpreted by 'kind'.
CREATE TABLE IF NOT EXISTS equipment (
    id          TEXT PRIMARY KEY,
    user_id     TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE,
    kind        TEXT NOT NULL CHECK (kind IN ('wing','foil')),
    name        TEXT NOT NULL,
    size        REAL NOT NULL,                    -- wing: m²  |  foil: cm²
    is_active    INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
    created_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_equipment_user ON equipment(user_id, kind);

-- --- Sessions -----------------------------------------------------------------
-- One logged wingfoil session == one feedback record (1:1). Feedback fields are
-- inlined here for simplicity; split out later only if multi-feedback is needed.
CREATE TABLE IF NOT EXISTS sessions (
    id                 TEXT PRIMARY KEY,
    user_id            TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE,
    spot_id            TEXT NOT NULL REFERENCES spots(id) ON DELETE RESTRICT,
    -- Spot-local calendar day. The API rejects any value != "today @ spot tz".
    session_date       TEXT NOT NULL,             -- 'YYYY-MM-DD'
    started_at         TEXT,                       -- ISO-8601 UTC, optional
    ended_at           TEXT,                       -- ISO-8601 UTC, optional
    wing_id            TEXT REFERENCES equipment(id) ON DELETE SET NULL,
    foil_id            TEXT REFERENCES equipment(id) ON DELETE SET NULL,

    -- ---- Feedback payload (the loop input) ----
    planed             INTEGER CHECK (planed IN (0,1)),
    -- Felt wind at lift-off in knots — feeds the planing-threshold calibration.
    planing_wind_kt    REAL,
    -- Subjective session quality and how well the forecast matched reality.
    rating             INTEGER CHECK (rating BETWEEN 1 AND 5),
    conditions_matched INTEGER CHECK (conditions_matched BETWEEN 1 AND 5),
    notes              TEXT,

    created_at         TEXT NOT NULL,
    updated_at         TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_user_date ON sessions(user_id, session_date);
CREATE INDEX IF NOT EXISTS idx_sessions_spot       ON sessions(spot_id);

-- --- Forecast snapshots -------------------------------------------------------
-- What was predicted at the moment feedback was given, so score-drift
-- (predicted vs. actual) can be measured later per source.
CREATE TABLE IF NOT EXISTS forecast_snapshots (
    id                        TEXT PRIMARY KEY,
    session_id                TEXT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    source                    TEXT NOT NULL
                                  CHECK (source IN ('open-meteo','weatherbit','era5','foil-score')),
    predicted_score           REAL,               -- Foil-Score 0..100 (foil-score source)
    predicted_wind_kt         REAL,
    predicted_window_start    TEXT,               -- ISO-8601 UTC
    predicted_window_end      TEXT,
    station_model_confidence  REAL,               -- 0..1 Station↔Model confidence
    raw_json                  TEXT,               -- full payload for audit/replay
    captured_at               TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_snapshots_session ON forecast_snapshots(session_id, source);

-- --- Entitlements (DORMANT — commercial groundwork) ---------------------------
-- Not used by v2.5.0 logic. Present so the future per-feature payment model
-- (MoR webhook -> upsert entitlement -> server-side feature gate) drops in with
-- no schema break. feature_key examples: 'multi_spot', 'extended_forecast'.
CREATE TABLE IF NOT EXISTS entitlements (
    id           TEXT PRIMARY KEY,
    user_id      TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE,
    feature_key  TEXT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'inactive'
                     CHECK (status IN ('active','inactive','expired','refunded')),
    source       TEXT,                            -- 'paddle' | 'stripe' | 'manual' | ...
    external_ref TEXT,                             -- provider subscription/order id
    expires_at   TEXT,                             -- ISO-8601 UTC, NULL = no expiry
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL,
    UNIQUE (user_id, feature_key)
);
CREATE INDEX IF NOT EXISTS idx_entitlements_lookup ON entitlements(user_id, feature_key, status);

-- --- Migration ledger ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS schema_migrations (
    version     TEXT PRIMARY KEY,
    applied_at  TEXT NOT NULL
);
